### ISSUE TITLE
Limit calendar days or months

### ISSUE THREAD

**Issue by sam-beri** [aleksanderwozniak/table_calendar#100]
Is it possible to limit the calendar days or months? 
For example I want to render just two months August and September. Somehow specifying a rang for date to be displayed...

**Comment by aleksanderwozniak** [comment]
Use [startDay](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/startDay.html) and [endDay](https://pub.dev/documentation/table_calendar/latest/table_calendar/TableCalendar/endDay.html) properties.

**Comment by vhessam** [comment]
When I use these properties, other dates get grayed! But I want to prevent user to select other months except selected range.

**Comment by craggy2593** [comment]
Hey, any potential progress on this, or any suitable workarounds? Also got the same need where the calendar needs to only show ±6 months, and would like a user to not be able to swipe any further, rather than simply having greyed out dates. 

Realise one way this can be achieved could be to set the `availableGestures` to none, and wrapping the calendar in a `GestureDetector` and managing custom logic that way, but then you obviously lose the animation, and feels rather hacky at best.

**Comment by aleksanderwozniak** [comment]
I have a working solution in my local branch - this will be added in `3.0.0` release, which should land there pretty soon.

**Comment by aleksanderwozniak** [comment]
Added in `3.0.0-beta` branch.

You can use it in your code by adding this to `pubspec.yaml`:

```yaml
  table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: 3.0.0-beta
```

**Comment by aleksanderwozniak** [comment]
Null safe 3.0.0 prerelease has been uploaded to pub.dev: https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0
