### ISSUE TITLE
The getter 'month' was called on null while trying to create custom header

### ISSUE THREAD

**Issue by badaween-ahmed** [aleksanderwozniak/table_calendar#147]
I am trying to create a custom header and I am getting this exception when I switch back to calendar from different screen. (Adding Builder() fixed the initial crash and now if I hot reload the app it loads without exception)
```
The getter 'month' was called on null.
Receiver: null
Tried calling: month
```
The code
```
Builder(
      builder: (context) =>  Text(
              _calendarController.focusedDay.toString(),
            ),
    ),
```
and the DateTime is not getting updated on change month. Don't know where to call setState()?

**Comment by aleksanderwozniak** [comment]
The null 'month' getter issue might happen because `_calendarController` needs to be initialized by `TableCalendar` widget. So methods like `_calendarController.focusedDay` should be called after the layout.

To rebuild your custom header widget, you can do as follows:
1) create a helper variable (DateTime) to store the focused day
2) use it directly for your header widget
3) in `TableCalendar`, use `onVisibleDaysChanged` callback to set this helper variable to `_calendarController.focusedDay`:
```dart
onVisibleDaysChanged: (_, __, ___) {
  setState(() {
    _headerDate = _calendarController.focusedDay;
  });
},
```

**Comment by badaween-ahmed** [comment]
I created a variable `DateTime focusDay = _calendarController.focusedDay;` inside the `Build()` method and passed down it to the HeaderWidget(focusDay) and still same error.

**Comment by aleksanderwozniak** [comment]
Try this: https://gist.github.com/aleksanderwozniak/bcc6ce5c2a341f778de32a9bf8e16dd1

**Comment by badaween-ahmed** [comment]
Yes, it's working. Thanks.
