### ISSUE TITLE
Displaying start/end time on each meeting

### ISSUE THREAD

**Issue by shaharsol** [aleksanderwozniak/table_calendar#148]
Can it be displayed in the event boxes?

**Comment by joielechong** [comment]
You can send the `List<YourObject>` instead of `List<String>` like the sample provided.

**Comment by logemann** [comment]
You mean the example? I dont see a List of objects in there when it comes to event entities. Do i miss something?

**Comment by joielechong** [comment]
I'm sorry, I give false message because of my sentence. Pardon me, english is not my main language.

> You mean the example? I dont see a List of objects in there when it comes to event entities. Do i miss something?

What I meant is, you can use your own object instead of List<String> in the example. You can change the 

[Map<DateTime, List> _events;](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart#L44)

to:

   Map<DateTime, List<YourObject>> _events;

then, whenever you have selected a day, you'll have the:

List<YourObject> _selectedEvents;

then construct your widget inside the [_buildEventList()](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart#L319)

**Comment by aleksanderwozniak** [comment]
Hmm, I should probably have an example with custom Event data class. But basically, it is what @joielechong wrote :)

@shaharsol
Do you want to have start/end hour visible in the particular day cell?

**Comment by joielechong** [comment]
> Hmm, I should probably have an example with custom Event data class. But basically, it is what @joielechong wrote :)

That's an important change that we need to use the library. I really hope I have that example before. I'm using a couple of hour digging the flutter code getting used the library. 

I think, the custom event data in the example is a good way to leverage this library usage.

**Comment by logemann** [comment]
Thanks for answering. I am already fireing away with my custom data type. Your plugin is really nice and i enjoy using it.

**Comment by shaharsol** [comment]
@aleksanderwozniak ended up using another package, but surely I'm gonna give this another look now. thanks.
