### ISSUE TITLE
Events that are several days long

### ISSUE THREAD

**Issue by wurstbrotfan** [aleksanderwozniak/table_calendar#160]
Hi there! I'm currently implementing your calendar plugin into my app. So far everything is working well, but I wasn't able to find an option for events that are several days long e.g. Jan 21 - Jan 24. Is this possible or do I need to create three separate events?

**Comment by aleksanderwozniak** [comment]
Yes, creating separate events sounds like the proper approach for the time being

**Comment by wurstbrotfan** [comment]
alright then I'll do that for now. thanks for the reply!

**Comment by runedrune** [comment]
Any plan on adding this in the future?

**Comment by aleksanderwozniak** [comment]
@runedrune 
Sure. I will be adding a bunch of other features first tho.

**Comment by runedrune** [comment]
Awesome. Just wanted to check if it's on the todo list. Thanks!

**Comment by ayush97123** [comment]
Hey, I have similar kind of question can I repeat events?
For ex -  If I create a event on Wednesday for 3 pm can I repeat that event for every week on Wednesday at 3 PM. Is there any property that I can set to create repeated events?

**Comment by aleksanderwozniak** [comment]
@ayush97123 
You would need to adjust the data yourself, since TableCalendar doesn't modify `events` and `holidays` in any way. You could use `List.generate()` to prepare recurring events, then pass that as a property to TableCalendar.

**Comment by aleksanderwozniak** [comment]
@wurstbrotfan @runedrune 
I've ultimately decided against adding an interface for events that span several days, because from calendar's point of view they need to be converted to `date: event` format anyway. I did however change the existing way that events are loaded into the calendar - now you can use a function that will give you a DateTime object, and expect you to return a list of events associated with that date:
```dart
List<T> Function(DateTime day) eventLoader
```
You will still need to transform the data, but this approach will be much more flexible to use.

@ayush97123 
This `eventLoader` mechanism has an interesting trait - you can now just check if the given `day` is a Wednesday, and if so - return your cyclic event. This should be much easier than having to generate the data beforehand.

**Comment by aleksanderwozniak** [comment]
3.0.0 prerelease with updated API has been uploaded to pub.dev: https://pub.dev/packages/table_calendar/versions/3.0.0-nullsafety.0
