### ISSUE TITLE
Hot reload 'value' called on null

### ISSUE THREAD

**Issue by Reprevise** [aleksanderwozniak/table_calendar#175]
Whenever I hot reload, I always get this error:

`The getter 'value' was called on null.`

It happens on line 35 of the `calendar_controller.dart` class:

```dart
CalendarFormat get calendarFormat => _calendarFormat.value;
```

Here's how I build the `TableCalendar`:

```dart
child: TableCalendar(
  calendarController: controller,
  availableCalendarFormats: const <CalendarFormat, String>{
    CalendarFormat.week: 'Week',
  },
  availableGestures: AvailableGestures.horizontalSwipe,
  initialCalendarFormat: CalendarFormat.week,
  startDay: DateTime.now().todaysDate,
  calendarStyle: const CalendarStyle(
    todayColor: Color(0xFF5459E0),
    contentPadding: EdgeInsets.zero,
  ),
  startingDayOfWeek: StartingDayOfWeek.monday,
  headerVisible: false,
  onDaySelected: onDaySelected,
),
```

**Comment by aleksanderwozniak** [comment]
I am unable to reproduce your issue, the code you provided seems to be working correctly for me. There might be an issue hidden inside the parent widget and/or inside `onDaySelected` callback.

**Comment by Reprevise** [comment]
Sorry I forgot to come back to this sooner, the issue resolved itself.

**Comment by antonyr** [comment]
This issue is reproducible, provided we build `TableCalendar` widget inside `StatelessWidget`, though CalendarController is instantiated, all the fields are still null as it can be seen below. Code is reformatted in my editor (VSCode) for calendar.dart. Also, the reason I am wrapping this in a stateless widget is that I am using external package [Get](https://github.com/jonataslaw/get) for state management.
![image](https://user-images.githubusercontent.com/539454/84482403-4aaaff80-acb5-11ea-84de-3940a8ae65b8.png)

What would be a solution for me in this case?

**Comment by antonyr** [comment]
I was able to resolve it myself after coming from the route given by `Get` microframework.
