### ISSUE TITLE
Remove calendar formats

### ISSUE THREAD

**Issue by lucas-sesti** [aleksanderwozniak/table_calendar#195]
How can i remove the calendar formats?

**Comment by luizwalber** [comment]
Yes you can, and that is easy, just insert the HeaderStyle inside TableCalendar

like this:
```
TableCalendar(
           .
           .
           .
           headerStyle: HeaderStyle(
                 centerHeaderTitle: true,
                 formatButtonVisible: false,
           ),
           .
           .
           .
);
```

**Comment by lucas-sesti** [comment]
Thank you, and i need one more answer, the events i marked in calendar, can i change color like one type of event is blue and other type event is red, can i do this?

**Comment by aleksanderwozniak** [comment]
@lucas-sesti 
Please keep one problem per issue in future. As for your question - this comment should have everything you need https://github.com/aleksanderwozniak/table_calendar/issues/183#issuecomment-582569009

Closing since this seems to be solved, feel free to open a new issue regarding event colors if needed.
