### ISSUE TITLE
setCalendarFormat error

### ISSUE THREAD

**Issue by caldwelladam** [aleksanderwozniak/table_calendar#203]
I have made the calendar format toggle button not visible in the header because I am using a dropdown button to determine the format. When I try to set the CalendarController format to week/month (outside of the build widget), I get an error:
_The setter 'value=' was called on null.
Receiver: null
Tried calling: value=Instance of 'CalendarFormat'_

It returns the same error if I try to print the current CalendarFormat through the controller as well.

**Comment by aleksanderwozniak** [comment]
Can you provide a self-contained example so that it can be easily reproduced?
Also, have a look at provided [example project](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/main.dart#L283), as it has all the functionality you have mentioned, albeit in a different form factor.

**Comment by caldwelladam** [comment]
I fixed the issue. All I did was add the setCalendarFormat lines to the onChanged function of the dropdown button widget. I'm not exactly sure why this worked though.

**onChanged: (String newValue) {
                                setState(() {
                                  layout = newValue;
                                  if (newValue == 'Week') {
                                    _calendarController.setCalendarFormat(CalendarFormat.week);
                                  }
                                  if (newValue == 'Month') {
                                    _calendarController.setCalendarFormat(CalendarFormat.month);
                                  }
                                });
                              },**

**Comment by aleksanderwozniak** [comment]
This is because you shouldn't really make any external changes inside `build` method (and since both `layoutToShow` and `showLayout` return a `Widget`, they are essentially `build` methods).

You should keep `_calendarController.setCalendarFormat()` just in `onChanged`, and remove it from those two other methods.
