### ISSUE TITLE
November 2 issue

### ISSUE THREAD

**Issue by romulo-arpini** [aleksanderwozniak/table_calendar#25]
Hi,

First of all thanks for this great plugin. I am curious though, because I think there is a small bug on every november. On the first sunday, the day is the same of the saturday. Example: December 2019, Sunday should have day 3, but it shows 2 instead. On Monday, it corrects itself and shows day 4.

Could you check if this is really happening or is something on my part?

I attached a screenshot showing this behavior. What is really strange is that it happens on every november I think. 

![Screenshot_20190328-184642](https://user-images.githubusercontent.com/42759891/55195196-92199e80-518a-11e9-84a9-7413b38a9394.jpg)

**Comment by romulo-arpini** [comment]
I think the bug may be elsewhere. Because on my device it happens the bug mentioned above but I just tested on the Android emulator and it works as expected.

**Comment by aleksanderwozniak** [comment]
This kinda looks like a daylight saving time issue, but I would check it just to be sure.
Could you do a little test on your device?

Open example project and replace `build` method with this:
```dart
@override
Widget build(BuildContext context) {
  return Scaffold(
    appBar: AppBar(
      title: Text(widget.title),
    ),
    body: Column(
      mainAxisSize: MainAxisSize.max,
      children: <Widget>[
        _buildTableCalendar(),
        const SizedBox(height: 24.0),
        Center(
          child: Text(
            _selectedDay.toString(),
            style: TextStyle().copyWith(fontSize: 20.0),
          ),
        ),
      ],
    ),
  );
}
```

Then run it on your device and navigate to November 2019.

It should look like this:
<img src=https://user-images.githubusercontent.com/22658673/55225710-88884900-5213-11e9-9759-50e4204091dd.png width=300>

Please comment here with a screenshot. 
I suspect it will say `2019-11-02 23:...` instead of `2019-11-03 00:...`

**Comment by romulo-arpini** [comment]
Aleksander, thanks for the quick response. You are right on point. It prints 2019-11-02 23:00:00.000.

And it's because of the daylight time saving like you mentioned that happens in the first weekend of november here.

So I guess I will have to import your project into mine and do a workaround? Because this seems to be a bug (or that's to be expected maybe?) in dart itself I guess.

**Comment by aleksanderwozniak** [comment]
That's quite a serious issue, as I want `TableCalendar` to be working properly anywhere.
Thanks for the report!

If you've got some time, you could try to fix the issue here and make a pull request. This might be a bit tricky tho, since like you already noticed, the issue lies not within `TableCalendar` per se, but within `DateTime` behavior.

If not, I should be available during next week, so I'll make necessary adjustments then.

**Comment by romulo-arpini** [comment]
I will definitely try to fix that, I just dont know how yet without butchering the code. But I will definitely make a pr if I can come up with something.

Thanks again!

**Comment by romulo-arpini** [comment]
Aleksander, I think with the new header builder you developed this issue can be easily fixed, so I am  closing this. Thank you!
