### ISSUE TITLE
[dev] markNeedsBuild error during programmatically set selectedDay

### ISSUE THREAD

**Issue by lcaprini** [aleksanderwozniak/table_calendar#260]
Hi! First of all, your package is awesome! There is all I'm looking for! Thank you very much.

I'm using the `dev` branch because of the new swiping method without the blank space, and I've an error during the programmatically set date in my StatefulWidget.

```dart
Column: (
  children: [
  Container(
    child: TableCalendar(
      selectedDay: _selectedDay,
      onDaySelected: (newDate, _) {
        setState(() {
          _selectedDay = newDate;
        });
      },
    ),
  ),
  FlatButton(
    child: Text('Today'),
    onPressed: () {
      setState((){
        _selectedDay = DateTime().now();
      });
    }
  ),
)
```

When I click on Today button I update the selected day with `setState`, but also the `onDaySelected` callback has call, and another `setState` runs, so the flutter app crash with the `setState() or markNeedsBuild()` error.

![Simulator Screen Shot - iPhone 8 - 2020-05-17 at 12 43 00](https://user-images.githubusercontent.com/8091030/82142422-82509400-983c-11ea-8cd8-89669452fcb3.png)

What I'm doing wrong?

Thanks,
--Luca

**Comment by aleksanderwozniak** [comment]
Hey Luca,

This is because you are essentially calling `setState()` twice. You can solve this by using a `SchedulerBinding` inside `onDaySelected` callback:

```dart
SchedulerBinding.instance.addPostFrameCallback((_) { 
  setState(() {
    // ...
  });
});
```

However, I would recommend finding a way to not rebuild the TableCalendar widget when `onDaySelected` gets called. Check this [example](https://github.com/aleksanderwozniak/table_calendar/blob/e7d4f34783e47e89d86bc4b289f39ddbefc66c14/example/lib/pages/complex_example.dart#L67) - only necessary widgets get rebuild there.
