### ISSUE TITLE
[FEAT] - Disable navigation when selecting invisible days in the next or previous month

### ISSUE THREAD

**Issue by royston-c** [aleksanderwozniak/table_calendar#318]
Hi, great work with this project!

Would it be possible to disable the navigation to the next/previous month when a date in the next/previous month is selected?

As far as I can see the `setSelectedDay` method on the `CalendarController` always updates the visible days via `_updateVisibleDays`.

https://github.com/aleksanderwozniak/table_calendar/blob/2cd1c7cabc3025bd227ce8cc2a32075d942a5df6/lib/src/calendar_controller.dart#L229-L233

Perhaps we could supply the formats that this animation is enabled for? Defaulting to the current implementaton, which would be all except `CalendarFormat.twoWeeks`? Something similar to:

```dart
 void _updateVisibleDays(bool isProgrammatic) { 
   if (!navigateInvisibleDaysForFormats.any((x) => x == calendarFormat)  || isProgrammatic) { 
     _visibleDays.value = _getVisibleDays(); 
   } 
 } 
```

**Comment by aleksanderwozniak** [comment]
Hi Roy,

I guess the question is if you want to prevent the month-swipe animation, or if you want to keep the current month visible.
Due to major internal changes, this animation is gone in version `3.0.0`.

If, however, you just want to keep the current month visible when tapping on days from previous/next month, then this unfortunately causes a lot of issues. 

For example, if your current month is January and you tap on February, then February gets focused. What will happen when you change calendar format from month to week/2-weeks? The only visible days will be from January, yet the focus will still be on February, meaning that the calendar header would display "February YYYY" even though none of the days from Feb are visible.

You could potentially use `outsideDaysVisible: false`. You won't have previous/next days visible, but you also don't get any problems related to them. This property only affects `CalendarFormat.month`, so in other formats all will be as usual.

**Comment by royston-c** [comment]
I guess my question is more based around the UX of the interaction.

By that I mean the user sees the dates in a table format. If, I as a user, click on any date in the table, would I expect table to change months? My personal opinion is no, as my intention isn't to navigate but to select a date. If I select a date, I already know what date it is. I don't need the widget to navigate to inform me the "1" I clicked on, next to the "31", is the next month (February in your example).

Also the interaction is at a date level but the navigation is at a month level. Meaning once the calendar does navigate I need to switch context to understand how my date level interaction has affected the whole calendar. Unlike the month navigation buttons, which are a month level interactions.

I think the same would hold true for the week or 2 weeks view because it is still just a table.

My suggestion was to have an override to allow the consumer to pick if the calendar should navigate on date selection. This library does such an excellent job at that. However, given your example perhaps the selected month should be the dominant one? (I.e. the one with the most dates shown). Then the only way to change the month is if the user chooses to do so via the month navigation buttons (or ideally swipe, but you mentioned some technical issues there)

**Comment by aleksanderwozniak** [comment]
I totally get your point regarding the UX. Switching the month as a reaction to date selection might seem a bit surprising at first, but there are non-obvious drawbacks to not doing so. It also only affects `CalendarFormat.month` and can be fully omitted by using `outsideDaysVisible: false`.

Consider this:

We start with `CalendarFormat.twoWeeks`. 

Depending on the focused date, switching the format to `CalendarFormat.month` will properly display either January, or February. This feels very natural - if I was focusing on a date belonging to January, I expect to see January after changing the format. 

Also note that there is no previous/next page jump on day selection in `CalendarFormat.twoWeeks`. It only occurs in `CalendarFormat.month`.

| Focus on Jan  | Focus on Feb |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/22658673/104130700-82c11080-5372-11eb-9055-26ca6ca6edb6.png" width="250">  | <img src="https://user-images.githubusercontent.com/22658673/104130721-9b312b00-5372-11eb-98fa-41cbdb5fe667.png" width="250"> |
| <img src="https://user-images.githubusercontent.com/22658673/104130704-89e81e80-5372-11eb-93f2-c73634c70ef2.png" width="250">  | <img src="https://user-images.githubusercontent.com/22658673/104130719-97050d80-5372-11eb-9c2e-506769b30669.png" width="250">  |


Now the same situation, but starting at `CalendarFormat.month`. 

The left screenshot is what would happen if there was no month jump in `CalendarFormat.month` - allowing you to select a date from outside "current" month. Now, if I change the format to `CalendarFormat.twoWeeks`, I expect the calendar to display days from February - I just selected a date belonging to that month. The widget, however, will display days from January. This could be acceptable (albeit strange), but note that also header is saying February, while visible days are from January - which is quite confusing.

In theory I could write some workaround to force it to display Feb, but I feel it might get very messy really quickly.


| Focus on Feb  | but showing days from Jan |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/22658673/104130963-f7e11580-5373-11eb-81a2-366083ec053b.png" width="250">  | <img src="https://user-images.githubusercontent.com/22658673/104130968-fb749c80-5373-11eb-8f57-7f5eb00ac56e.png" width="250"> |


The solution to this problem is that either we accept month jumps when days outside of current month are selected, or we just hide them via `outsideDaysVisible: false`.

Another solution would be to display those days, but prevent users from selecting them. They could still trigger `onDaySelected` (or maybe `onUnavailableDaySelected`) callback, but just skip the internal handling - so nothing would happen in terms of calendar's UI. That way those days would still be visible, however in order to select them users would have to change the month (or calendar format) first. 

Let me know what you think about this idea.

**Comment by royston-c** [comment]
I see, so the issue lies in changing the format of the calendar.

Personally I would expect the top Month Year indicator to show the selected month. In your last example this would be January 2021. I wouldn't expect it to represent the month of the selected date. The selected date is a transient state and somewhat unrelated to the Month Year in the header.

Just in case it helps to explore the options, this is my use case. My app allows a user to assign a meal to a selected date. The meal plans are organised into weeks. Thus it makes sense to display the weeks in full. For instance, if I am planning my meals for a week that spans 2 months (2020-**11**-30 to 2020-**12**-06) I'd want to see all the days and have the ability to select any of them. Thinking about it, the solution to my use case might be a 4 week option that acts like the 2 week one.

<img src="https://user-images.githubusercontent.com/5285498/104133384-3c23e400-537b-11eb-8bb2-71143e61c642.png" height="500">

I don't think your final solution would work for the above. However, if I could monitor the `onUnavailableDaySelected` then programatically change the selected day without triggering the change to the selected month, this would work. Feels a little counter intuitive, though. Hence why I suggested the change to `_updateVisibleDays`. I can see this has been removed in v3 but maybe something similar?

https://github.com/aleksanderwozniak/table_calendar/blob/2cd1c7cabc3025bd227ce8cc2a32075d942a5df6/lib/src/calendar_controller.dart#L229-L233

**Comment by aleksanderwozniak** [comment]
That's actually a very neat idea!

Check `3.0.0-dev-navigation` branch, I have added the modified code there.

If you want to try it, you can add it to your project by replacing your current pubspec.yaml lines with this:
```yaml
  table_calendar:
    git:
      url: git://github.com/aleksanderwozniak/table_calendar.git
      ref: 3.0.0-dev-navigation
```

If all goes well and this doesn't break other functionalities and behaviors, I will add it to official release. I might even make it the default behavior, since this month navigation on tap is something that I'm not completely happy with.

**Comment by royston-c** [comment]
Fantastic!

I'll have a look now. I'm still on v2. Are there any breaking changes or docs on updating?

**Comment by aleksanderwozniak** [comment]
There is a lot of internal changes due to the fact that I had to include PageView widget there, but from public API perspective I feel this should be quite easy to migrate. Mainly CalendarController got removed, meaning that now you would just pass the data to widget itself. So for example, instead of calling `calendarController.setSelectedDay(...)`, you would now rebuild the widget with updated `selectedDay` property.

I'm in the process of making a null-safe version and then preparing the docs, so sadly they are not available yet. You can check the [new examples](https://github.com/aleksanderwozniak/table_calendar/tree/3.0.0-dev-navigation/example/lib/pages) though, I think they should point you in the right direction.

**Comment by royston-c** [comment]
Got it. Thanks. That version behaves exactly as I'd expect. 

The only issue I have is with the `events`. Nothing comes through to `markersBuilder`. It seems you have changed the internal dates to UTC. The ones I used with v2 were in the device's timezone (e.g. GMT). Might be worth documenting that for anyone updating.

**Comment by royston-c** [comment]
Also, at first glance, I'm unsure what the `focusedDate` is vs the `selectedDate`?

**Comment by royston-c** [comment]
Other than the above the update was pretty smooth. Nice work! The removal of the controller really simplifies the widget.

The interactions feel far slicker now that the months don't jump without me explicitly changing them.

I also implemented a week selector recently using the `dayBuilder`. This change makes that more intuitive as well. 👍

**Comment by aleksanderwozniak** [comment]
Try wrapping your events with `LinkedHashMap`, and set equality rule to compare just the date-part of two DateTimes:
https://github.com/aleksanderwozniak/table_calendar/blob/5202ee1e668b1ea5ae6c4ff0f968990eda4d63b0/example/lib/pages/events_example.dart#L26-L30
Let me know if that helped with local dates.

As for `focusedDate` and `selectedDate`, both of those were available earlier via controller. The difference is that `selectedDate` is just the currently highlighted date, whereas `focusedDate` determines which month will be marked as "current". Most of the time they will be actually the same date (and that was the default implementation of `onDaySelected`, which funnily enough prevented implementing your idea :smiley:).

Having both available grants you more control over what is happening with the widget: `focusedDate` can be used to jump between months, while `selectedDate` is only responsible for highlighting one specific date.

This also means that to recreate earlier `controller.setSelectedDate()` behavior, you need to rebuild the widget with both `selectedDate` (to highlight) and `focusedDate`(to focus month):
https://github.com/aleksanderwozniak/table_calendar/blob/5202ee1e668b1ea5ae6c4ff0f968990eda4d63b0/example/lib/pages/complex_example.dart#L278-L286

**Comment by royston-c** [comment]
Thanks for the suggestion and explanation. Very helpful. I think from my perspective this ticket is solved with your changes.

On a separate note while I'm looking at the API for `events`. It might be nice to have a callback to get the events for a particular date. Personally, I find creating a `Map<DateTime, List<T>>` ahead of time a little cumbersome.

Maybe a `List<T> getEvents(DateTime date)` property might simplify things? Obviously a breaking change but one you might consider while v3 is under development? Only a suggestion mind.

Lastly, great work with this library, one of the best Flutter libs I've used. Super flexible.

**Comment by aleksanderwozniak** [comment]
Glad it all works well!

> On a separate note while I'm looking at the API for `events`. It might be nice to have a callback to get the events for a particular date. Personally, I find creating a `Map<DateTime, List<T>>` ahead of time a little cumbersome.
> 
> Maybe a `List<T> getEvents(DateTime date)` property might simplify things? Obviously a breaking change but one you might consider while v3 is under development? Only a suggestion mind.

Do you mean something in the lines of `dayBuilder`, but instead of assigning a custom widget to a date, you would assign a list of events?

**Comment by royston-c** [comment]
I mean a change in the public API of `TableCalendar`

```Dart

TableCalendar(
  //events: widget.events, <-- remove the map and instead let the widget asks for the events it needs, when it needs them via getEvents
  getEvents: (date) { // <-- new addition to the API
    return myEvents.where((x) => x.date == date).toList();
  },
  onDaySelected: (DateTime day, DateTime _, List events, List holidays) {
    _selectedDay = day;
  },
  selectedDay: _selectedDay,
}
```

I bring it up because I had to understand the internal workings to find out that the dates had changed to UTC. Instead, the `getEvents` callback functions exposes the fact the date is UTC during debugging (instead of digging through the source code) and allows for simpler logic compared to being forced to create a `Map<DateTime, List<T>>`. 

The obvious drawbacks are the potential for poorly performing code but this is now the consumer's concern and they have full control. For example, they could still use a map. Also, it is a breaking change, however, the change is a simple one as the map can be used on the `getEvents` callback.

This would bring it more in line with the builder pattern we see in Flutter, although we aren't building widgets just returning data.

**Comment by royston-c** [comment]
Not sure your thoughts but this might be a slight code smell? In that, the widget returns a subset of data you gave it, which I could easily have calculated myself without the `TableCalendar` widget. For instance, the API could be changed to:

```Dart
List<MyEeventClass> _myEvents;

Widget _buildTableCalendar() {
  return TableCalendar(
    //events: widget.events, <-- no need for events at all
    onDaySelected: (DateTime date, DateTime _, List holidays) { // <-- no need to pass the events to each callback
      _selectedDay = day;
      var events = _getEvents();
      //... use my events if I need them.
    },
    selectedDay: _selectedDay,
  }
}

List<dynamic> _getEvents(DateTime date) {
 return _myEvents.where((x) => x.date == date).toList();
}
```

The only use of the events that aren't callbacks is `isEventDay` in the `_CellWidget`. This could easily be removed along with `eventDayStyle` and the style for that cell is calculated via `dayBuilder` or similar?

Might be too large a change for you to consider but the widget would only be responsible for the date types it implicitly knows about (Weekday, Weekend, Today, Yesterday etc) and let the consumer worry about the rest. Holidays would also fall under the same rule as events I think.

This would follow open/close a little better. Then when the consumer needs to implement something that isn't an event or holiday they would just follow the same pattern they already do for holidays and events. Instead of asking you for a change to lib. Not to mention it simplifies the internal code.

This library exposes so much and is so flexible that locking in concepts such as events and holidays might actually hinder it in the long run.

Or we could use composition and create an Events and Holidays TableCalendar (`EventsAndHolidayTableCalendar`) that uses the super generic `TableCalendar`. The `EventsAndHolidayTableCalendar` widget can then have the same API as the v2 (minus the controller).

**Comment by aleksanderwozniak** [comment]
That's something I wondered about some time ago - releasing a `TableCalendarLite` of sorts, without splitting the `build` method of cells into each possible variant like `isWeekend`, `isOutside`, `isOutsideWeekend`, `isEvent`, `isEventOutside`, etc., because there can be an endless amount of use-cases that don't matter for most of the package users, and all of those variants can be added by users when needed via `dayBuilder`. Same applies for other specialized builders.

The reason I've kept everything as is, is because I like the plug and play aspect of this package. Users can do
```dart
TableCalendar(events: _events)
```
and they get a pretty much fully functional widget with minimal work required. 

Due to aforementioned variants, styling is super simple - want to change weekend color from default red to blue?
```dart
TableCalendar(
  events: _events,
  calendarStyle: CalendarStyle(
    weekendStyle: TextStyle(color: Colors.blue),
  ),
),
```

However, like I said, I had some thoughts about making a more stripped-down version of the widget. It would definitely require more work from users, but at the same time it would paradoxically grant more freedom and control over the UI with a single builder, not to mention the lack of unnecessary if-checks.

I'll give it some more thought and see what I come up with. To be honest I wanted to already publish the `3.0.0` prerelease since it is pretty much complete, but I'll hold on with it for a moment.

As for the events - the main reason for passing them into the widget, is to get the event markers in UI. `onDaySelected` callback returns a subset of that data, which might seem redundant, however since this subset is already required for event markers, it makes sense to pass it back with callback. Besides simplicity, it acquires the data from map just once, instead of potentially acquiring it twice.

All of this would not matter for `TableCalendarLite`, because event markers would be added by users inside `dayBuilder`, thus defeating the main reason for passing events to `TableCalendar`. This means that `TableCalendarLite` would definitely be without `events` property.

I'm thinking about having both of those widgets - `TableCalendar` with all the features built-in and ease of use, and `TableCalendarLite` with work (but also power) delegated to user. Final widget names yet to be figured out.

Regarding `getEvents` builder - I like it a lot. It wasn't quite possible to use when `CalendarController` was back around, but now it makes a lot of sense. Performance should be more or less the same when a map is used there, yet at the same time this will allow more flexibility in ways of supplying events. And there is also another hidden bonus - you don't need to rebuild the whole widget when splitting events into chunks of 3 months (i.e. no need for `setState()` inside `onPageChanged()`). It will still require rebuilding when updating events in currently visible month, though.

**Comment by royston-c** [comment]
I just thought that if you add a `getEvents` callback that returns a `List<T>` you would need a hook to force a `setState` on the `TableCalendar` when the events change. I guess this is a primary reason why the builder pattern returns widgets that can re-render themselves, independent of their parents.

I totally get what you're saying regarding the `Lite` version, it's a difficult one. I don't think the events and holidays concepts hinder the developer in any way. It only clutters the API slightly and leads me to ask you for changes rather than building them myself. However, this could be mitigated with documentation of how to extend via the `dayBuilder`.

**Comment by aleksanderwozniak** [comment]
> I just thought that if you add a `getEvents` callback that returns a `List<T>` you would need a hook to force a `setState` on the `TableCalendar` when the events change. I guess this is a primary reason why the builder pattern returns widgets that can re-render themselves, independent of their parents.

Do you have some idea how this hook could be implemented? Or some simple example showcasing this mechanism?

**Comment by royston-c** [comment]
Sorry, I think I'm incorrect. As long as the parent calls setState when the events change. Then it should cascade down and force the TableCalendar to call the callback. Ignore me!

However, to answer the question anyway I think the most common way is to assign a `GlobalKey` to the widget and call `_globalKey.currentState.setState((){ })` to force a widget re-build from outside the current widget tree.

**Comment by aleksanderwozniak** [comment]
No worries! This parent `setState()` call is what I meant by _"It will still require rebuilding when updating events in currently visible month, though."_ 

I think besides using a `GlobalKey` some observable could be used. But I'll leave that to package users if they want to implement it on their end, since it would make more sense to use some more advanced state management there.

One more thing - I noticed you are using `TableCalendar` in a dialog. From the UX/UI perspective, how do you feel about the vertical autosizing in month format - I mean scaling between 5-weeks and 6-weeks, instead of always showing 6-weeks (even when the whole bottom week would be from next month)?

**Comment by royston-c** [comment]
I personally think it works very well. The animation of the size change is very natural. 👍 

If the developer has a problem they can always add it to a fixed height (same as 6 weeks) container.

<video src="https://user-images.githubusercontent.com/5285498/104724648-e2c80600-5728-11eb-9401-b9bd9f47b681.mp4" height="500">

**Comment by aleksanderwozniak** [comment]
Looks awesome! Nice job on the app 🚀 

I've ultimately decided to split the package into 3 usable widgets which build on one another:

- TableCalendar - provides UI + interactivity. Very plug and play.
- TableCalendarLite - delegates UI to users, provides interactivity. UI is completely custom, UX is same as TableCalendar's.
- TableCalendarBase - delegates UI and interactivity to users. User gets a calendar widget that swipes left and right, but any onTap handling needs to be added if needed. This allows to implement pretty much any custom behavior, while making sure that all calendar related stuff is handled properly.

If you want to, you can check them out in `3.0.0-beta` branch. I've also included date range selection mode there, further enhancing the default interactivity.

Thanks for your insight Roy, it was definitely helpful!
