### ISSUE TITLE
Calendar not working error when apk created

### ISSUE THREAD

**Issue by SinanKanmaz** [aleksanderwozniak/table_calendar#331]
First of all thank you for this beautiful library.  Everything works fine when working on the emulator. However, when I build apk, I only see a gray screen on the calendar page. I could not figure out the reason for this. I would be glad if you could help.

**Comment by aleksanderwozniak** [comment]
Hi, I just checked it with [example project](https://github.com/aleksanderwozniak/table_calendar/tree/2.3.0-stable/example) and everything seems to be working fine for me. Can you check if the same error happens when you build apk of example project?

Also, make sure to use the latest `2.3.0` version.

**Comment by SinanKanmaz** [comment]
First of all, thank you for your interest. This solved my problem. The problem was caused by the expanded widget I used. I wrapped it up with a flex widget and the problem was solved. Thank you again.
