### ISSUE TITLE
Holiday support

### ISSUE THREAD

**Issue by espenandreassen79** [aleksanderwozniak/table_calendar#35]
Great calendar!

However:
- It would be nice with holiday support, by. e.g. an interface witch ppl can implement their own holiday rules.
- Multiple markes that can also support multiple icons (eg. in the down-left corner)

**Comment by aleksanderwozniak** [comment]
I agree, adding holiday support sounds like a good idea.

As for customizing markers - have you tried using [Calendar Builders](https://pub.dartlang.org/documentation/table_calendar/latest/table_calendar/CalendarBuilders-class.html)? You can also take a look in example project.

Do you have any suggestions about displaying holiday rules? Eg. different text color / different background / additional markers (via builders)

**Comment by espenandreassen79** [comment]
Hello,

When it comes to Holiday support, I was thinking on an interface like "public bool IsHoliday(DateTime date)". Then people can write theire own logic into it.

When it comes to customizing markers:
I am new to Flutter/Dart, so I thought the example main.dart, line 220, was mandatory Text child.
child: Text(
                  '${events.length}',
                  style: TextStyle().copyWith(
                    color: Colors.white,
                    fontSize: 12.0,
                  ),
Now, I have learned that I can replace Text to a Row of Images, if I want.

However, the Interface does only support ONE marker, and it is places in the right bottom. It would be great with yet another marker, in the left corner :)

Colors:
According to my calander that I find in the store. The holiday is marked in the color red, as same as sundays. That should be the default color, but people should be able to override it.

WeekendStyle: I don't like that you handle both Saturday and sunday the same. Many people work on saturday, and people has different salery on sauturday vs. sunday. You should have SaturdayStyle and SundayStyle instead of WeekendStyle, or maybe all of them.

Regards

**Comment by aleksanderwozniak** [comment]
#39 resolves all of this by adding revamped markers API and holiday support :tada:

First, update your package version to `1.2.0`.

New markers API uses a list of widgets, instead of a single widget. This allows for a much more refined customization -> provide as many icons as you want. Then you can wrap each of them with `Positioned` widget to control their layout (see example project).

For holidays, take a look [here](https://github.com/aleksanderwozniak/table_calendar#holidays).

As for splitting `weekendStyle` into 2 entities, I suggest a different solution - just use a custom Builder:
```dart
weekendDayBuilder: (context, date, _) {
  TextStyle style;

  if (date.weekday == 7) {
    // Sunday
    style = TextStyle().copyWith(color: Colors.red);
  } else {
    // Saturday
    style = TextStyle().copyWith(color: Colors.purple);
  }

  return Center(
    child: Text(
      '${date.weekday}',
      style: style,
    ),
  );
},
```
Note that you will also need to provide `selectedDayBuilder` and `todayDayBuilder`, but they follow the same template. Take a look at example project - then using them should be clear.
