### ISSUE TITLE
How to improve the calendar builder on tap event

### ISSUE THREAD

**Issue by khangpt** [aleksanderwozniak/table_calendar#362]
I wonder when I tap on an day cell on calendar, the calendar seem call the builder all of cell in this calendar (in spite of touching only one cell). It's become slow performance and lagging render on layout. Can you show me the cheat way or the solution to resolve this issue. Thanks

**Comment by manhlhvm** [comment]
you can show code ?

**Comment by aleksanderwozniak** [comment]
Rebuilding cells is pretty much unavoidable. Performance will mostly depend on how you are using the widget - perhaps your callbacks are doing too much work, resulting in slower performance? Hard to tell without looking at the code.

Be sure to check it in release mode, since it is much faster than debug mode.

You can also try using `3.0.0-dev` branch, it should have better performance.
