### ISSUE TITLE
Test breaking with a A RenderFlex overflowed

### ISSUE THREAD

**Issue by shinta5150** [aleksanderwozniak/table_calendar#38]
I create a simple StatefulWidget with just a TableCalendar, but it throws an error "A RenderFlex overflowed by 65 pixels on the bottom" when I try write a test.
I've stripped it down to just a widget with just the calendar, and it still breaks.

```
import 'package:flutter/material.dart';
import 'package:table_calendar/table_calendar.dart';

class CalendarScreen extends StatefulWidget {
  @override
  CalendarScreenState createState() => CalendarScreenState();
}

class CalendarScreenState extends State<CalendarScreen> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('testCalendar'),
      ),
      body: Column(
          mainAxisSize: MainAxisSize.max,
          children: <Widget>[
            TableCalendar(locale: 'en_US'),
          ]
      ),
    );
  }
}
```

and the Test

```
import 'package:flutter_test/flutter_test.dart';

import 'package:test_calendar/screens/calendar_screen.dart';

void main() {
  testWidgets('Load calendar screen smoke test', (WidgetTester tester) async {
    // Build our app and trigger a frame.
    await tester.pumpWidget(CalendarScreen());
  });
}
```

**Comment by aleksanderwozniak** [comment]
This happens because default viewport size of WidgetTester is 800x600:
```dart
const Size _kDefaultTestViewportSize = Size(800.0, 600.0);
```

Table Calendar uses available width to calculate its height. WidgetTester has more width than height, which causes RenderFlex overflow.

You can fix your issue 2 ways:
- Inside the test itself -> set viewport size to square (or preferably vertical rectangle)
```dart
void main() {
  final TestWidgetsFlutterBinding binding = TestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('Calendar test', (WidgetTester tester) async {
    await binding.setSurfaceSize(Size(640, 640));

    await tester.pumpWidget(MyApp());
  });
}
```
- Inside the actual UI -> by simply wrapping `TableCalendar` with a `SizedBox` with some smaller, reasonable width
```dart
body: Column(
  mainAxisSize: MainAxisSize.max,
  children: <Widget>[
    SizedBox(
      width: 300,
      child: TableCalendar(),
    ),
  ],
),
```

Unless you want your Calendar UI to have fixed width, you should go with option 1 here

**Comment by shinta5150** [comment]
Awesome. Thank you for your speedy response. Love the widget!
Have opted for option 2 and all is working
