### ISSUE TITLE
table_calendar - beta branch

### ISSUE THREAD

**Issue by woogi-kang** [aleksanderwozniak/table_calendar#426]
Hello there, thanks for this amazing library! 

We are currently using your package ( beta-branch ) on our production. 
Are you going to delete this branch when the pre-released version goes to stable? 

If so, can you give us some time to migrate to Flutter 2.0v? We are having some problems migrating to 2.0v because of other packages. 

Again, thanks for this library!

**Comment by aleksanderwozniak** [comment]
Hi,

Yes, that was the general plan, especially since null safety has landed on Flutter stable now.

Have you tried running your app in [unsound null safety mode](https://dart.dev/null-safety/unsound-null-safety)? This should allow you to use packages with and without null safety support at the same time.

**Comment by woogi-kang** [comment]
Hi, 

Thanks for fast response. I will try the method you offered. But one thing I am curious about is that is this method just upgrading the version of Dart or do I have to upgrade both Dart and Flutter bins?

**Comment by aleksanderwozniak** [comment]
You will need to run this on Flutter 2.0

**Comment by woogi-kang** [comment]
Thanks a lot! Successfully migrated to 2.0

**Comment by aleksanderwozniak** [comment]
Cheers!
