### ISSUE TITLE
Feature Request: Horizontal Scroll week days instead of swiping

### ISSUE THREAD

**Issue by tonydavidx** [aleksanderwozniak/table_calendar#429]
would it be possible to scroll the days like a horizontal list view instead swiping.

**Comment by aleksanderwozniak** [comment]
Yes, I can add this to the following update for v3.0.0

**Comment by tonydavidx** [comment]
thank you, the package was very useful.

**Comment by aleksanderwozniak** [comment]
Unfortunately implementing this with a PageView widget (using `pageSnapping: false`) as a base for scrolling runs into far more issues than I initially expected... Basically any external state update messes up the behavior due to scroll offset getting refreshed in hard to predict manner. A lot of interesting features of TableCalendar would have to be sacrificed to get this to work properly. 

As such I will have to ultimately drop this request - feel free to try to modify the source code to customize it to your needs. Perhaps using a ListView instead of a PageView might work out better.
