### ISSUE TITLE
onVisibleDaysChanged show current month/year

### ISSUE THREAD

**Issue by marcuslma** [aleksanderwozniak/table_calendar#43]
Hi,

I'm not sure if there is available a way to retrieve the current month/year on the onVisibleDaysChanged when visible period changes (month, 2 weeks, week).
But if not, it would be nice to have it. I load the events of current year, so would be nice to have the possibility.

**Comment by aleksanderwozniak** [comment]
Yes, there is. You are given the `first` and `last` visible day, both of them are of `DateTime` type -> this means you can simply use `first.year` and `first.month` to get the displayed year and month.

There is a small catch about month, since there can be some extra visible days before and after the current month. Two ways to solve it:

1. Use CalendarStyle to hide them -> onVisibleDaysChanged callback will adjust:
```dart
calendarStyle: CalendarStyle(
  outsideDaysVisible: false,
),
```

2. Add a week or so to the `first` day:
```dart
final temp = first.add(const Duration(days: 7));
final currentMonth = temp.month;
final currentYear = temp.year;
```

Note that you probably will need to fine-tune it to your situation, since current CalendarFormat will also play a role here.

**Comment by aleksanderwozniak** [comment]
Now there is even easier way, added with #84.

Update the package to version `2.0.0`, then follow [these steps](https://github.com/aleksanderwozniak/table_calendar#installation).

Here is the property you are looking for: `_calendarController.focusedDay`

**Comment by marcuslma** [comment]
Hello!
Thank you, I will try it soon as possible.
:+1: :clap:
