### ISSUE TITLE
Keeping calendar State between Screens

### ISSUE THREAD

**Issue by rmpw** [aleksanderwozniak/table_calendar#430]
Hello!

Thank you for making this amazing product available to us ! :) 

I would need some guidance in the following please:

I am using the TableCalendar() on multiple screens, each screen displaying the calendar itself, when I switch between screen the updated value does not reflect on the former screen. I am assuming this would be an issue with the state the calendar is in.

To note that the screens where i added the calendars have their own classes.
I am using version ^3.0.0-nullsafety.1 ,

Kindly if you can advise on this please, I saw others posted issues regarding  this on version 2.3.3 but unfortunately I couldn't replicate the workaround over there. As I understood from the comments of that post, a feature will be implemented on 3.0.0> in order to make the states be kept between screens.

Thank you again for this!

**Comment by aleksanderwozniak** [comment]
Hi,

I would suggest keeping the actual calendar's state above both of the screens, so that it can be shared between them (for example you can make a MobX store for them). The idea is to rebuild the widget on either screen with updated values that are stored in a place that is accessible to both screens.

**Comment by aleksanderwozniak** [comment]
I think this can be closed by now.
