### ISSUE TITLE
[null-safety] Focused day is not set when opening calendar

### ISSUE THREAD

**Issue by bdremynoel** [aleksanderwozniak/table_calendar#442]
In version 3.0.0-nullsafety.1, calendar has no focused day on UI.
Only visible and refreshed when changing selected day.

**Comment by SergeyLabutin** [comment]
I found workaround, if set property rangeEndDay without setting rangeStartDay

`rangeEndDay: c.selectedDay.value,`

But +1 for using focusedDay property for this case.

**Comment by aleksanderwozniak** [comment]
Focused day is not marked in UI by design.

You can use some builder to mark it though - for example [prioritizedBuilder](https://pub.dev/documentation/table_calendar/3.0.0-nullsafety.1/table_calendar/CalendarBuilders/prioritizedBuilder.html).

**Comment by bdremynoel** [comment]
I'm confused, maybe I wasn't clear or using wrong attribute now.

When opening calendar how to get a default selection? In V2, I used `initialSelectedDay`...

**Comment by aleksanderwozniak** [comment]
In v3.0.0 you can use `selectedDayPredicate` in the same manner - simply set the `_selectedDay` to some initial value. 

Check the example below:
https://github.com/aleksanderwozniak/table_calendar/blob/7a979b846d6926032978257a4754e8a0f36b653a/example/lib/pages/table_events_example.dart#L19-L30

**Comment by bdremynoel** [comment]
Oh, my bad I see my error now, my default value has hours, minutes, ...

Just another question for V3, firstDay / lastDay are required and non-nullable. Is it intended ?
For now, I just set it to big values.

**Comment by aleksanderwozniak** [comment]
I would recommend using `isSameDay` to compare dates, as it omits their time values: https://github.com/aleksanderwozniak/table_calendar/blob/7a979b846d6926032978257a4754e8a0f36b653a/example/lib/pages/table_events_example.dart#L97

That's correct, both `firstDay` and `lastDay` are needed now because of a PageView widget inside the internal code. They are also used to setup scroll boundaries, such that users can't navigate past them. For an "unlimited" calendar simply pass some dates that are far enough not to be reached by manual swiping.

**Comment by bdremynoel** [comment]
Thanks for the help and clarification!
