### ISSUE TITLE
No calendar controller in 3.0?

### ISSUE THREAD

**Issue by eugenemiko** [aleksanderwozniak/table_calendar#453]
Will the calendar controller return back in future 3.x releases? It was simple to control selected day from outside of the widget. How is it supposed to be done now? Just pass a new value and redraw then?
Also, calendar now does not auto-scroll to the page with selected day.

**Comment by aleksanderwozniak** [comment]
Please check the README file for 3.0.0 for a guide on how to use it. https://github.com/aleksanderwozniak/table_calendar/issues/153#issuecomment-772881560 has some info on CalendarController.

**Comment by eugenemiko** [comment]
> Please check the README file for 3.0.0 for a guide on how to use it. [#153 (comment)](https://github.com/aleksanderwozniak/table_calendar/issues/153#issuecomment-772881560) has some info on CalendarController.

Thanks. I feel some "feature degradation" after 3.x release. Now there is no option for calendar to automatically scroll to focused day if it was changed from outside of the widget (programmatically). I do not have a proper API for this now.

**Comment by eugenemiko** [comment]
@aleksanderwozniak I think we probably need a boolean option like "automaticPageScrolling" to make this happen.

**Comment by aleksanderwozniak** [comment]
Remember that you can still update the focused day to any valid value, as well as use the PageController that's associated with the calendar widget:

https://github.com/aleksanderwozniak/table_calendar/blob/0bd7c55d46c41e2caf62e06ffa337b0a72ef6701/example/lib/pages/complex_example.dart#L109-L135

I'd say that lack of a built-in scrolling animation when setting a new focused day is a very small cost considering all the major improvements and features added in 3.0.0.

Feel free to play with the PageController; it can be used for changing and animating pages. Since this seems important to you, I also encourage you to submit a pull request that would implement it in 3.0.0.

**Comment by aleksanderwozniak** [comment]
Added with https://github.com/aleksanderwozniak/table_calendar/pull/478
