### ISSUE TITLE
Markers missing in v3.0.0

### ISSUE THREAD

**Issue by elvisgn** [aleksanderwozniak/table_calendar#471]
Hi,
With the changes in v3.0.0, I find that my markers are not showing up anymore. On tap of a day, the events exist, but they don't show as markers.

I tried creating MarkerBuilder within CalendarBuilders but still not seeing anything.

Kindly help.

Thanks.

**Comment by aleksanderwozniak** [comment]
Hi, I'd suggest checking the [events example](https://github.com/aleksanderwozniak/table_calendar/blob/master/example/lib/pages/events_example.dart) and this [guide](https://github.com/aleksanderwozniak/table_calendar#events). You might need to use `LinkedHashMap` instead of the default `Map` for events.

**Comment by elvisgn** [comment]
Got it. The eventLoader "day" had a time portion that never matched my event time.

Thanks.
