### ISSUE TITLE
first day of the month not visible when scrolling 2 weeks

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [aleksanderwozniak/table_calendar#535]
Hi,

We have recently found an issue - when scrolling through 2 weeks calendar we do not see first days of the month

https://user-images.githubusercontent.com/3918999/123827330-3316d700-d909-11eb-9233-04ec7ba3ae90.mp4

**Comment by aleksanderwozniak** [comment]
Looks correct to me - they are next to the end of the previous month.

**Comment by vytautas-pranskunas-** [comment]
So if I have full month view and move to the next month - why next month shows them?

**Comment by aleksanderwozniak** [comment]
That would always duplicate days of the first week of new month when in 2 weeks format, or it would mean having a big hole at the end of the old month, neither of which I like.

What you see here is by design. Month format due to its nature can be split by each month; 2 weeks format feels more intuitive when it is continuous.
