### ISSUE TITLE
Show CalendarFormat.year 

### ISSUE THREAD

**Issue by mraaz97** [aleksanderwozniak/table_calendar#576]
I would like to show whole year Format of calendar. How can I achieve that?

**Comment by aleksanderwozniak** [comment]
Year format is not supported. You can display the following formats: month, two weeks, one week.

**Comment by mraaz97** [comment]
Will you consider adding that format anytime soon?

**Comment by aleksanderwozniak** [comment]
At this moment I don't have any plans of adding another format, especially since year format would look so much different than what is currently in the package. 

Depending on what you are going after, this might be quite easy to implement on your own. Especially if by "year format" you mean a month selector with all 12 months displayed at the same time.

**Comment by mraaz97** [comment]
That's exactly what I want to achieve. Speaking of pseudo code, what would I need to do to get that year format?

**Comment by aleksanderwozniak** [comment]
Sounds like a simple 4x3 grid with buttons would be enough.
