### ISSUE TITLE
Please expose chevron icon tap events

### ISSUE THREAD

**Issue by moshe5745** [aleksanderwozniak/table_calendar#625]
I want to "catch" the moment the user interacts with the calendar, so I could fetch new data that corresponds to the new dates of the calendar.
First, so I could fetch the data right away, and second to show a spinner. 

Now we only have `onPageChanged`. So we have this event only after the animation of the month/week is finished.

It would be convenient to have some event when the user taped on the chevrons(right and left).

**Comment by moshe5745** [comment]
#626

**Comment by aleksanderwozniak** [comment]
Doing it this way, you will end up with two different behaviors when a calendar page is changed - performing a horizontal swipe will yield a different outcome than tapping on a chevron.

If you want to override the chevron tap anyway, you can just provide a custom header altogether, like in [this example](https://github.com/aleksanderwozniak/table_calendar/blob/3abf0e7f67f2e7069d5869cdbeda9fe2b8048cb4/example/lib/pages/complex_example.dart#L109).

**Comment by moshe5745** [comment]
Didn't get you about the "two different behaviors", but I will try the example you provided. Thanks.
Do you want me to close my PR?

**Comment by aleksanderwozniak** [comment]
What I mean, is that `onPageChanged` gets called whenever the current page gets changed, regardless of the way it was triggered (chevron tap or page swipe). Adding `onChevronTap` callback and fetching data there will affect only the chevron tap; thus whenever someone swipes the page, that aforementioned data fetch will not occur. That's why I think it is better to handle it just via `onPageChanged`.

You can of course proceed with the custom header approach, and for example lock horizontal swipe gesture with [AvailableGestures](https://pub.dev/documentation/table_calendar/latest/table_calendar/AvailableGestures.html).

**Comment by moshe5745** [comment]
Oh, of course, you're right. I basically disabled the swipe.
But you are right that it must target both ways. So I guess it's better to be onPageChangeStart. So we can trigger a WS fetch and show a spinner right away.

**Comment by aleksanderwozniak** [comment]
> After a second thought, I think a better approach to this will be just to load the previous and next month/week data. Without spinners and this onPageChangeStart complexity.

Yeah, this is exactly the approach I would recommend. It also avoids running into UI issues during page transition (like the previously visible page suddenly "missing" its events, because they are now replaced by a new set of events - another reason to keep data for 3 pages at once).

**Comment by aleksanderwozniak** [comment]
Looks like this can be closed by now - closing the related PR as well.
