### ISSUE TITLE
disable swipe for days of week

### ISSUE THREAD

**Issue by denny6389** [aleksanderwozniak/table_calendar#687]
Is it possible to disable animation for dow (make it not moveable) and make it swipeable only for the content row? 
Right now both dow and content row get swipped even though the dow part does not have any change.

**Comment by aleksanderwozniak** [comment]
Correct, that's by design. To achieve non-moveable dow you could hide it along with the default header, and provide a custom header that also displays days of week:

1. TableCalendar config
```dart
daysOfWeekVisible: false,
headerVisible: false,
```

2. Custom header widget example
https://github.com/aleksanderwozniak/table_calendar/blob/999905422ad098f2ad79d3e1099cc05655d778d1/example/lib/pages/complex_example.dart#L196
