### ISSUE TITLE
Markers no longer showing with 2.0.1

### ISSUE THREAD

**Issue by PaitoAnderson** [aleksanderwozniak/table_calendar#98]
I just updated from 1.2.5 to 2.0.1 and noticed the markers aren't rendering anymore, not sure how to fix just yet. The only change I made was adding a `CalendarController`.

Before: 
![Simulator Screen Shot - iPhone X - 2019-08-27 at 17 02 41](https://user-images.githubusercontent.com/4108718/63807924-c5548b00-c8ec-11e9-9ec7-559ff8d39118.png)

After:
![Simulator Screen Shot - iPhone X - 2019-08-27 at 17 01 44](https://user-images.githubusercontent.com/4108718/63807923-c5548b00-c8ec-11e9-9014-9cffe753eb20.png)

**Comment by aleksanderwozniak** [comment]
My guess is that you are loading events on each month change.

TableCalendar 2.0.0+ handles events differently than previous versions. You should load all of them on startup, and let the package do the rest for you. Unfortunately, doing this is not always possible, which is why I will take a deeper look into this issue when I get some free time.

For the time being, you could:

1. Load all events on startup
2. Revert to 1.2.5 and keep things the old way
3. Try solutions from #86

Nice design btw, I really dig it :)

**Comment by PaitoAnderson** [comment]
Thank you for fixing this, it works well for me now.

I also appreciate the compliment on the design, I couldn't have done it without your awesome calendar though :)
